-- ⚠️ ADVERTENCIA: ESTO BORRARÁ LOS DATOS EXISTENTES ⚠️

-- 1. Limpieza
DROP TABLE IF EXISTS votes;
DROP TABLE IF EXISTS group_members;
DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS profiles;

-- 2. Perfiles (Vinculado a Supabase Auth)
CREATE TABLE profiles (
  id UUID REFERENCES auth.users(id) PRIMARY KEY,
  email TEXT,
  display_name TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Votos
CREATE TABLE votes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  voter_id UUID REFERENCES profiles(id),
  voted_for_id UUID REFERENCES profiles(id),
  rating INTEGER CHECK (rating >= 1 AND rating <= 5),
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Poblar profiles desde usuarios existentes
INSERT INTO public.profiles (id, email, display_name)
SELECT
  id,
  email,
  COALESCE(raw_user_meta_data->>'display_name', split_part(email, '@', 1))
FROM auth.users;

-- 5. Trigger para crear perfil automáticamente al registrarse
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, display_name)
  VALUES (
    new.id,
    new.email,
    COALESCE(new.raw_user_meta_data->>'display_name', split_part(new.email, '@', 1))
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 6. Habilitar Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE votes;

-- 7. Políticas de Seguridad (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE votes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Acceso total a autenticados" ON profiles FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Acceso total a autenticados" ON votes FOR ALL USING (auth.role() = 'authenticated');
